name: CI

on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: |
          git submodule update --init
          zig build --summary all
          zig build -Dtarget=x86_64-linux-gnu --summary all
